# This workflow creates docker container from hcrystalball repository including jupyter
# enabling fast start-up when launching binder to interactively explore code examples
# from https://github.com/jupyterhub/repo2docker-action#use-github-actions-to-cache-the-build-for-binderhub
name: Build Binder Notebook Container

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout files in repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
